version: '3.8'

services:
  # API service that handles HTTP requests
  api:
    build: .
    ports:
      - "5090:5090"
    environment:
      - NODE_ENV=production
      - MEMORY_CACHE_TTL=300
      - HTTP_PORT=5090
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVICE_MODE=api
      - WORKER_COUNT=12
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  # Redis for communication between API and workers
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Worker services using improved worker implementation
  worker:
    build: .
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVICE_MODE=worker
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 12
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  redis-data:
