# Docker Compose configuration for Marine Traffic Scraper
# version field is obsolete in newer Docker Compose versions

services:
  # API service that handles HTTP requests
  api:
    build: .
    ports:
      - "5032:5090"
    environment:
      - NODE_ENV=production
      - MEMORY_CACHE_TTL=300
      - HTTP_PORT=5090
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVICE_MODE=api
      - WORKER_COUNT=6  # Updated to match the number of worker replicas
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=marine_traffic
      - DB_USER=mt_user
      - DB_PASSWORD=mt_password
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
    stop_grace_period: 30s  # Allow time for graceful shutdown

  # Redis for communication between API and workers
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    stop_grace_period: 30s

  # Worker services using improved worker implementation
  worker:
    build: .
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVICE_MODE=worker
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 12  # Reduced from 12 to 6 to lower resource usage
      resources:
        limits:
          cpus: '1'
          memory: 1G
    stop_grace_period: 30s  # Allow time for graceful shutdown

volumes:
  redis-data:
